### ISSUE TITLE
AttributeError: 'module' object has no attribute 'get_global_step'

### ISSUE THREAD

**Issue by SeekPoint** [songgc/TF-recomm#3]
rzai@rzai00:~/prj/TF-recomm$ python svd_train_val.py
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "svd_train_val.py", line 97, in <module>
    svd(df_train, df_test)
  File "svd_train_val.py", line 60, in svd
    _, train_op = ops.optimization(infer, regularizer, rate_batch, learning_rate=0.001, reg=0.05, device=DEVICE)
  File "/home/rzai/prj/TF-recomm/ops.py", line 27, in optimization
    global_step = tf.train.get_global_step()
AttributeError: 'module' object has no attribute 'get_global_step'
rzai@rzai00:~/prj/TF-recomm$

**Comment by songgc** [comment]
Please try Tensorflow version r.012, in which there is [tf.train.get_global_step()](https://www.tensorflow.org/api_docs/python/train/training_utilities)
