### ISSUE TITLE
Do Item Item recommendation

### ISSUE THREAD

**Issue by amit2103** [songgc/TF-recomm#7]
Hi,

is it possible to do do recommendation based on similar items only without any user-item ranking?

**Comment by songgc** [comment]
If you all force users' IDs to be 0, it removes user information, which can be regarded as creating a global user.

**Comment by amit2103** [comment]
I don't have also any user data only item data. So you are saying I can
just feed users with Id 0 and then how should I proceed with running the
filtering with only the items file and no user file?

**Comment by songgc** [comment]
In your case, the user file is not needed. You can set USER_NUM=1 and create global (virtual) user with ID 0.  For inference, user ID should be 0 as well.
